name: builders_act_maker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  theme_tailor_annotation: ^2.0.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  get_it: ^7.6.0

  google_fonts: ^4.0.5
  intl: ^0.18.0

  app_runner: ^2.2.0+1
  fluent_ui: ^4.6.1
  dyn_mouse_scroll: ^1.0.7
  go_router: ^7.1.1
  flutter_reorderable_grid_view: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^2.1.0
  flutter_lints: ^2.0.1
  custom_lint: ^0.4.0

  build_runner: ^2.4.4
  flutter_gen_runner: ^5.3.1
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  theme_tailor: ^2.0.0

  flutter_launcher_icons: ^0.13.1
  go_router_builder: ^2.0.2


flutter:
  uses-material-design: true
 